#:schema node_modules/wrangler/config-schema.json
name = "eduscript-nk"
main = "server.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Folder hasil build Vite
[assets]
directory = "dist"
binding = "ASSETS"

# Environment Variables (Non-Rahasia)
[vars]
CF_R2_PUBLIC_URL = "https://pub-edbc7b36889448d6b89d209ec6a8301a.r2.dev"
CF_R2_BUCKET_NAME = "eduscript-assets"

# Binding Database D1
[[d1_databases]]
binding = "DB"
database_name = "eduscript-db"
database_id = "6e0fcb5d-8325-4b81-b9ca-9189a950b240"

# Binding R2 Storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "eduscript-assets"
